import AppKit
import Foundation
import UniformTypeIdentifiers

enum ClipboardContent: Equatable {
    case text(String)
    case image(data: Data, type: NSPasteboard.PasteboardType)
}

struct ClipboardHistoryItem: Identifiable, Equatable {
    let id: UUID
    var content: ClipboardContent
    var copiedAt: Date
    var isPinned: Bool

    init(
        id: UUID = UUID(),
        content: ClipboardContent,
        copiedAt: Date = Date(),
        isPinned: Bool = false
    ) {
        self.id = id
        self.content = content
        self.copiedAt = copiedAt
        self.isPinned = isPinned
    }

    var title: String {
        switch content {
        case let .text(value):
            let oneLine = value
                .components(separatedBy: .whitespacesAndNewlines)
                .filter { !$0.isEmpty }
                .joined(separator: " ")
            return oneLine.isEmpty ? "Text" : oneLine
        case .image:
            return "Image"
        }
    }

    var detail: String {
        switch content {
        case let .text(value):
            if URL(string: value.trimmingCharacters(in: .whitespacesAndNewlines))?.scheme != nil {
                return "Link"
            }
            return "Text · \(value.count) character\(value.count == 1 ? "" : "s")"
        case let .image(data, _):
            return "Image · \(Int64(data.count).formattedBytes)"
        }
    }

    var systemImage: String {
        switch content {
        case let .text(value):
            return URL(string: value.trimmingCharacters(in: .whitespacesAndNewlines))?.scheme != nil
                ? "link"
                : "text.alignleft"
        case .image:
            return "photo"
        }
    }

    func matches(_ query: String) -> Bool {
        let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !needle.isEmpty else { return true }
        return title.localizedCaseInsensitiveContains(needle)
            || detail.localizedCaseInsensitiveContains(needle)
    }
}

/// Session-local clipboard history. Nothing captured here is written to disk.
/// Password managers can mark entries as concealed or transient; those entries
/// are deliberately ignored.
@MainActor
final class ClipboardHistoryService: ObservableObject {
    @Published private(set) var items: [ClipboardHistoryItem] = []
    @Published private(set) var isPaused = false

    private static let ignoredTypes = Set([
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ])
    private static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png,
        NSPasteboard.PasteboardType(UTType.jpeg.identifier),
        .tiff
    ]
    private static let maximumTextLength = 100_000
    private static let maximumImageBytes = 20 * 1_024 * 1_024

    private let pasteboard: NSPasteboard
    private let capacity: Int
    private var observedChangeCount: Int
    private var timer: Timer?

    init(pasteboard: NSPasteboard = .general, capacity: Int = 30) {
        self.pasteboard = pasteboard
        self.capacity = max(capacity, 1)
        self.observedChangeCount = pasteboard.changeCount
    }

    var isEmpty: Bool { items.isEmpty }

    func start(interval: TimeInterval = 0.65) {
        guard timer == nil else { return }
        observedChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            onMainActor { self?.captureIfChanged() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func setPaused(_ paused: Bool) {
        guard isPaused != paused else { return }
        isPaused = paused
        // Do not ingest everything copied while capture was paused.
        observedChangeCount = pasteboard.changeCount
    }

    func togglePaused() {
        setPaused(!isPaused)
    }

    /// Public for deterministic tests and for an immediate refresh when the
    /// widget becomes active. Normal capture is driven by the timer.
    func captureIfChanged() {
        let changeCount = pasteboard.changeCount
        guard changeCount != observedChangeCount else { return }
        observedChangeCount = changeCount
        guard !isPaused, !containsIgnoredType else { return }
        guard let content = readContent() else { return }
        insert(content)
    }

    func copy(_ item: ClipboardHistoryItem) {
        pasteboard.clearContents()
        switch item.content {
        case let .text(value):
            pasteboard.setString(value, forType: .string)
        case let .image(data, type):
            pasteboard.setData(data, forType: type)
        }
        observedChangeCount = pasteboard.changeCount
        touch(item.id)
    }

    func togglePinned(_ item: ClipboardHistoryItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        sortItems()
    }

    func remove(_ item: ClipboardHistoryItem) {
        items.removeAll { $0.id == item.id }
    }

    func clear() {
        items.removeAll()
    }

    func seedForPreview(_ samples: [ClipboardHistoryItem]) {
        items = samples
        sortItems()
        trimToCapacity()
    }

    private var containsIgnoredType: Bool {
        !Set(pasteboard.types ?? []).isDisjoint(with: Self.ignoredTypes)
    }

    private func readContent() -> ClipboardContent? {
        for type in Self.imageTypes {
            if let data = pasteboard.data(forType: type),
               !data.isEmpty,
               data.count <= Self.maximumImageBytes {
                return .image(data: data, type: type)
            }
        }

        guard let value = pasteboard.string(forType: .string),
              !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              value.count <= Self.maximumTextLength else { return nil }
        return .text(value)
    }

    private func insert(_ content: ClipboardContent) {
        if let index = items.firstIndex(where: { $0.content == content }) {
            var existing = items.remove(at: index)
            existing.copiedAt = Date()
            items.append(existing)
        } else {
            items.append(ClipboardHistoryItem(content: content))
        }
        sortItems()
        trimToCapacity()
    }

    private func touch(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].copiedAt = Date()
        sortItems()
    }

    private func sortItems() {
        items.sort {
            if $0.isPinned != $1.isPinned { return $0.isPinned }
            return $0.copiedAt > $1.copiedAt
        }
    }

    private func trimToCapacity() {
        guard items.count > capacity else { return }
        items.removeLast(items.count - capacity)
    }
}
