import AppKit
import ImageIO
import Foundation
import UniformTypeIdentifiers

enum ClipboardContent: Equatable {
    case text(String)
    case image(data: Data, type: NSPasteboard.PasteboardType)
}

struct ClipboardHistoryItem: Identifiable, Equatable {
    let id: UUID
    var content: ClipboardContent
    var copiedAt: Date
    var isPinned: Bool

    init(
        id: UUID = UUID(),
        content: ClipboardContent,
        copiedAt: Date = Date(),
        isPinned: Bool = false
    ) {
        self.id = id
        self.content = content
        self.copiedAt = copiedAt
        self.isPinned = isPinned
    }

    var title: String {
        switch content {
        case let .text(value):
            let oneLine = value
                .components(separatedBy: .whitespacesAndNewlines)
                .filter { !$0.isEmpty }
                .joined(separator: " ")
            return oneLine.isEmpty ? "Text" : oneLine
        case .image:
            return "Image"
        }
    }

    var detail: String {
        switch content {
        case let .text(value):
            if URL(string: value.trimmingCharacters(in: .whitespacesAndNewlines))?.scheme != nil {
                return "Link"
            }
            return "Text · \(value.count) character\(value.count == 1 ? "" : "s")"
        case let .image(data, _):
            return "Image · \(Int64(data.count).formattedBytes)"
        }
    }

    var systemImage: String {
        switch content {
        case let .text(value):
            return URL(string: value.trimmingCharacters(in: .whitespacesAndNewlines))?.scheme != nil
                ? "link"
                : "text.alignleft"
        case .image:
            return "photo"
        }
    }

    func matches(_ query: String) -> Bool {
        let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !needle.isEmpty else { return true }
        return title.localizedCaseInsensitiveContains(needle)
            || detail.localizedCaseInsensitiveContains(needle)
    }
}

/// Session-local clipboard history. Nothing captured here is written to disk.
/// Password managers can mark entries as concealed or transient; those entries
/// are deliberately ignored.
@MainActor
final class ClipboardHistoryService: ObservableObject {
    @Published private(set) var items: [ClipboardHistoryItem] = []
    @Published private(set) var isPaused = false

    private static let ignoredTypes = Set([
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ])
    private static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png,
        NSPasteboard.PasteboardType(UTType.jpeg.identifier),
        .tiff
    ]
    private static let maximumTextLength = 100_000
    private static let maximumImageBytes = 20 * 1_024 * 1_024
    /// Images are kept in memory, and thirty full-screen screenshots of a 5K
    /// display is well over half a gigabyte for a menu-bar utility. Past this
    /// total the oldest unpinned images are let go; text is never evicted for it.
    static let imageBudgetBytes = 80 * 1_024 * 1_024
    nonisolated private static let textTypes: Set<NSPasteboard.PasteboardType> = [
        .string,
        NSPasteboard.PasteboardType("public.utf8-plain-text"),
        .rtf,
        .html
    ]

    private let pasteboard: NSPasteboard
    private let capacity: Int
    private var observedChangeCount: Int
    private var timer: Timer?
    private let thumbnails = NSCache<NSUUID, NSImage>()

    init(pasteboard: NSPasteboard = .general, capacity: Int = 30) {
        self.pasteboard = pasteboard
        self.capacity = max(capacity, 1)
        self.observedChangeCount = pasteboard.changeCount
    }

    var isEmpty: Bool { items.isEmpty }

    func start(interval: TimeInterval = 0.65) {
        guard timer == nil else { return }
        observedChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            onMainActor { self?.captureIfChanged() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func setPaused(_ paused: Bool) {
        guard isPaused != paused else { return }
        isPaused = paused
        // Do not ingest everything copied while capture was paused.
        observedChangeCount = pasteboard.changeCount
    }

    func togglePaused() {
        setPaused(!isPaused)
    }

    /// Public for deterministic tests and for an immediate refresh when the
    /// widget becomes active. Normal capture is driven by the timer.
    func captureIfChanged() {
        let changeCount = pasteboard.changeCount
        guard changeCount != observedChangeCount else { return }
        observedChangeCount = changeCount
        guard !isPaused, !containsIgnoredType else { return }
        guard let content = readContent() else { return }
        insert(content)
    }

    func copy(_ item: ClipboardHistoryItem) {
        pasteboard.clearContents()
        switch item.content {
        case let .text(value):
            pasteboard.setString(value, forType: .string)
        case let .image(data, type):
            pasteboard.setData(data, forType: type)
        }
        observedChangeCount = pasteboard.changeCount
        touch(item.id)
    }

    func togglePinned(_ item: ClipboardHistoryItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        sortItems()
    }

    func remove(_ item: ClipboardHistoryItem) {
        items.removeAll { $0.id == item.id }
        thumbnails.removeObject(forKey: item.id as NSUUID)
    }

    func clear() {
        items.removeAll()
        thumbnails.removeAllObjects()
    }

    /// A small decoded copy of an image item for its list row.
    ///
    /// Decoding the stored bytes in the row's `body` re-decoded a full-size
    /// image — a screenshot can be tens of megapixels — on every re-render and
    /// every scroll step, for a 25pt square.
    func thumbnail(for item: ClipboardHistoryItem) -> NSImage? {
        guard case let .image(data, _) = item.content else { return nil }
        let key = item.id as NSUUID
        if let cached = thumbnails.object(forKey: key) { return cached }

        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: 96
        ]
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary)
        else { return nil }
        let thumbnail = NSImage(
            cgImage: image,
            size: NSSize(width: image.width, height: image.height)
        )
        thumbnails.setObject(thumbnail, forKey: key)
        return thumbnail
    }

    func seedForPreview(_ samples: [ClipboardHistoryItem]) {
        items = samples
        sortItems()
        trimToCapacity()
    }

    private var containsIgnoredType: Bool {
        !Set(pasteboard.types ?? []).isDisjoint(with: Self.ignoredTypes)
    }

    private func readContent() -> ClipboardContent? {
        let types = pasteboard.types ?? []
        // A file copied in Finder carries its icon as a TIFF and its name as
        // text. Neither is what was copied — the file is — and recording the
        // icon as an "Image" entry was just noise.
        guard !types.contains(.fileURL) else { return nil }

        let text = pasteboard.string(forType: .string).flatMap { value -> String? in
            guard !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                  value.count <= Self.maximumTextLength else { return nil }
            return value
        }
        if let text, !Self.prefersImage(in: types) { return .text(text) }

        for type in Self.imageTypes {
            if let data = pasteboard.data(forType: type),
               !data.isEmpty,
               data.count <= Self.maximumImageBytes {
                return .image(data: data, type: type)
            }
        }
        return text.map(ClipboardContent.text)
    }

    /// Whether the source app offers an image ahead of any text.
    ///
    /// Pasteboard types are listed in the source's order of preference. Office
    /// and iWork attach a picture of copied text or cells as a courtesy for
    /// apps that cannot read their formats; taking any image first recorded
    /// those copies as "Image" and lost the text. A screenshot or an image
    /// copied from a browser lists the image first, and stays an image.
    nonisolated static func prefersImage(in types: [NSPasteboard.PasteboardType]) -> Bool {
        let imageTypes: Set<NSPasteboard.PasteboardType> = [
            .png, .tiff, NSPasteboard.PasteboardType(UTType.jpeg.identifier)
        ]
        guard let firstImage = types.firstIndex(where: imageTypes.contains) else { return false }
        guard let firstText = types.firstIndex(where: textTypes.contains) else { return true }
        return firstImage < firstText
    }

    private func insert(_ content: ClipboardContent) {
        if let index = items.firstIndex(where: { $0.content == content }) {
            var existing = items.remove(at: index)
            existing.copiedAt = Date()
            items.append(existing)
        } else {
            items.append(ClipboardHistoryItem(content: content))
        }
        sortItems()
        trimToCapacity()
    }

    private func touch(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].copiedAt = Date()
        sortItems()
    }

    private func sortItems() {
        items.sort {
            if $0.isPinned != $1.isPinned { return $0.isPinned }
            return $0.copiedAt > $1.copiedAt
        }
    }

    private func trimToCapacity() {
        if items.count > capacity {
            items.removeLast(items.count - capacity)
        }

        // Newest first, so the walk keeps recent images and drops old ones.
        var imageBytes = 0
        items.removeAll { item in
            guard case let .image(data, _) = item.content else { return false }
            imageBytes += data.count
            return imageBytes > Self.imageBudgetBytes && !item.isPinned
        }
    }
}
