import type { Metadata } from 'next';
import LegalPage from '@/components/LegalPage';

export const metadata: Metadata = {
  title: 'Privacy Policy — Bondex Notch',
  description: 'How Bondex Notch handles website, support, and on-device app data.',
  alternates: { canonical: '/privacy/' },
};

export default function PrivacyPage() {
  return (
    <LegalPage
      currentPath="/privacy/"
      eyebrow="Your data stays yours"
      title="Privacy Policy"
      intro="Bondex Notch is designed to work locally on your Mac. This policy explains the limited information involved when you use the website, contact support, or run the app."
    >
      <section>
        <h2>1. Who we are</h2>
        <p>
          Bondex Notch is independently developed and operated by Rithy Bondeth
          in Cambodia. Privacy questions and requests can be sent to{' '}
          <a href="mailto:rithybondeth999@gmail.com?subject=Bondex%20Notch%20privacy">
            rithybondeth999@gmail.com
          </a>
          .
        </p>
      </section>

      <section>
        <h2>2. Website information</h2>
        <p>
          The public website does not currently create user accounts, run
          advertising trackers, or intentionally set analytics cookies. Our
          hosting and infrastructure providers may process ordinary request
          information—such as IP address, browser type, requested page, and
          timestamp—to deliver the site, prevent abuse, and maintain security.
          Their retention periods are controlled by their own systems.
        </p>
      </section>

      <section className="legal-callout">
        <h2>3. Checkout preview</h2>
        <p>
          The current checkout is a product preview. Card fields are validated
          inside your browser and are not transmitted to Bondex, stored, or used
          to charge a card. No purchase is completed and no production licence is
          issued through that preview. When payments open, this policy and the
          checkout will identify the payment provider before you submit payment.
          Bondex does not intend to store full card numbers or security codes.
        </p>
      </section>

      <section>
        <h2>4. Information inside the Mac app</h2>
        <p>
          Preferences, Quick Captures, licence state, shelf references, and
          integration settings are stored locally on your Mac. Clipboard history
          is session-only, remains in memory, and ignores content marked concealed
          or transient by the source application. Bondex does not operate a cloud
          account that receives this content.
        </p>
        <ul>
          <li>Automation access is used to read and control supported media apps.</li>
          <li>Files and Folders access is used to observe your Downloads folder.</li>
          <li>Calendar access is used for optional upcoming-meeting features.</li>
          <li>Notifications access lets Bondex show alerts generated by Bondex.</li>
          <li>On-device capture enhancement runs only when you request it on a supported Mac.</li>
        </ul>
        <p>
          If a media source supplies a remote album-art URL, Bondex may retrieve
          that image from the source&apos;s content server. As with any network
          request, that server can receive basic connection information such as
          your IP address.
        </p>
      </section>

      <section>
        <h2>5. Messages and support</h2>
        <p>
          If you contact us by email, Instagram, Telegram, or WhatsApp, we receive
          the information you choose to send and the account details exposed by
          that service. We use it to answer your request, provide support, manage
          a purchase or refund, prevent abuse, and keep necessary business
          records. Those communication services apply their own privacy terms.
        </p>
      </section>

      <section>
        <h2>6. Sharing, sale, and retention</h2>
        <p>
          We do not sell personal information. We may share limited information
          with service providers that host the site, process future payments, or
          help deliver support; when legally required; or to protect users and the
          service. Support and transaction records are kept only as long as
          reasonably needed for those purposes, legal obligations, disputes, and
          fraud prevention.
        </p>
      </section>

      <section>
        <h2>7. Your choices and rights</h2>
        <p>
          You can disable optional app permissions in macOS System Settings and
          remove local app data by deleting it from the app or your Mac. You may
          email us to ask what contact or transaction information we hold about
          you, request a correction or deletion, or object to a use of that
          information. We may need to verify your request and may retain records
          when the law requires it. Rights provided by applicable law remain
          available regardless of this summary.
        </p>
      </section>

      <section>
        <h2>8. Security, children, and changes</h2>
        <p>
          We use reasonable safeguards, but no storage or transmission method is
          completely secure. Bondex is a general-audience productivity utility
          and is not directed to children under 13. We may update this policy as
          payments, hosting, or app features change. The date above will change
          when a revision takes effect.
        </p>
      </section>
    </LegalPage>
  );
}
